# RSSB Sewadar Management - CI/CD Pipeline
# 
# Automated build and deployment to Firebase Hosting
# Triggers on push to main branch and handles both frontend and backend builds

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Environment variables
env:
  NODE_VERSION: '18'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies for backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci --only=production

      # Install dependencies for frontend  
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # Create backend environment file
      - name: Create backend .env
        run: |
          cd backend
          echo "DATABASE_URL=./database/sewadar.db" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "PORT=5000" >> .env
          echo "CORS_ORIGINS=https://${{ secrets.FIREBASE_HOSTING_URL }}" >> .env

      # Create frontend environment file
      - name: Create frontend .env
        run: |
          cd frontend
          echo "REACT_APP_API_URL=https://${{ secrets.FIREBASE_HOSTING_URL }}/api" >> .env
          echo "REACT_APP_NAME=RSSB Sewadar Management" >> .env
          echo "REACT_APP_VERSION=1.0.0" >> .env
          echo "GENERATE_SOURCEMAP=false" >> .env

      # Initialize backend database
      - name: Initialize database
        run: |
          cd backend
          npm run migrate
          npm run seed

      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Create build directory structure
      - name: Prepare deployment files
        run: |
          mkdir -p dist
          # Copy frontend build
          cp -r frontend/build/* dist/
          # Copy backend files
          mkdir -p dist/api
          cp -r backend/src dist/api/
          cp -r backend/package*.json dist/api/
          cp -r backend/database dist/api/
          # Create API startup script
          echo '{"name":"rssb-api","scripts":{"start":"node src/server.js"},"dependencies":{"express":"^4.18.2","cors":"^2.8.5","helmet":"^7.1.0","bcryptjs":"^2.4.3","jsonwebtoken":"^9.0.2","joi":"^17.12.1","express-rate-limit":"^7.1.5","winston":"^3.11.0","dotenv":"^16.4.5","better-sqlite3":"^9.4.0","uuid":"^9.0.1","swagger-ui-express":"^5.0.0","swagger-jsdoc":"^6.2.8"}}' > dist/api/package.json

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Post-deployment notification
      - name: Deployment Success Notification
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 Frontend: https://${{ secrets.FIREBASE_HOSTING_URL }}"
          echo "🚀 API: https://${{ secrets.FIREBASE_HOSTING_URL }}/api"
          echo "📖 Docs: https://${{ secrets.FIREBASE_HOSTING_URL }}/api/docs"

      # Handle deployment failure
      - name: Deployment Failure Notification  
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "Check the logs above for error details."
          exit 1

  # Health check job (runs after deployment)
  health-check:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Health Check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          
          # Check frontend
          echo "🔍 Checking frontend..."
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ secrets.FIREBASE_HOSTING_URL }}")
          if [ $response -eq 200 ]; then
            echo "✅ Frontend is healthy"
          else
            echo "❌ Frontend health check failed (HTTP $response)"
            exit 1
          fi
          
          # Check API health endpoint
          echo "🔍 Checking API..."
          api_response=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ secrets.FIREBASE_HOSTING_URL }}/api/health")
          if [ $api_response -eq 200 ]; then
            echo "✅ API is healthy"
          else
            echo "❌ API health check failed (HTTP $api_response)"
            exit 1
          fi
          
          echo "🎉 All systems operational!"

  # Security scan (optional job)
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run security audit
        run: |
          cd backend && npm audit --audit-level=high
          cd ../frontend && npm audit --audit-level=high
          
      - name: Security scan passed
        run: echo "🔒 Security scan completed successfully"